{% set name = "atomap" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c3b02ca58e7628e318302014129ca7bcdaaa5717f4bc8bb441e5fd068e135c6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - scipy >=1.4.0
    - numpy >=1.13
    - h5py
    - matplotlib-base >=3.1.0
    - tqdm
    - scikit-image >=0.17.1
    - scikit-learn
    - hyperspy-base >=1.5.2, <2.0.0
    - numba
    - ase >=3.17.0
    - exspy

test:
  imports:
    - atomap
  commands:
    - export MPLBACKEND=agg  # [unix]
    - set MPLBACKEND=agg  # [win]
    - python -c "import atomap.api"

about:
  home: https://atomap.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Library for analysing atomic resolution images'
  description: |
    Atomap is a Python library for analysing atomic resolution
    scanning transmission electron microscopy images.
    It relies on fitting 2-D Gaussian functions to every atomic
    column in an image, and automatically finding all the atomic
    planes with the largest spacings.
  doc_url: https://atomap.org/install.html
  dev_url: https://gitlab.com/atomap/atomap

extra:
  recipe-maintainers:
    - magnunor
