travis:
  secure:
    BINSTAR_TOKEN: Kxcg3J5kRjoUzO5uAUvT4p1vXPvKH643a3aRX+gpiOnt2Rik//SfHYqJgOtdtE22nIIUm2c2DzY3soAzW21RX+8XuZAoCpfqEG5LBt/X6IiqcYdroHyvCmEXlILFtwslICrB3uZPu2F5uJ6ULl+1yKDlPADpQ816sd4+FeEMuBeK54TyXbDIz2xaKWTxJxcHVTt/4WBLMfD70nulIyG0RhWEx4frw3AeQx6BP7wQsiEcBIlHTL5hS0f4TdU41893eJlqb4N06JcdpODoBTBfNDy2DpXEPKxjREntVX1fvn74iESG5pFXFbmruCQYVXQmE1KuVerDIZ9XAUZ1APKIWVEklYNIjGrDKKuaD3lgVfrEBjHcVt7qKl6KKMIxDnustl1Y6lUBhyzNCr8XP2YReYRzBjiBAYT/71dp9n75wXd49bmVY7WYFHa+5cF5x00KuuK86UU+wCJcwVKKPyvQkwEbPYMj91eNQTKaLM9OgOUUfw1WFa3pIOT9dtY5c/kgjdSukPa6sLeYjYIdZY0nQ3pYY3ogz0ZIoKd0mEKwbiKPsBmaMlDcI750SaDjvj9gzgUhi2J/QSthu6HsELW0BJ+BpL8gI44ej18Rz2TjE+i+CAKuv+2bT3yZdpXAz0aiVyPlR4wXF+cn9ZwP3K4i4QJr3oyMvQLiY3V5hY0Pt/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
